### ISSUE TITLE
Role mapping is not allowing multiple lines to be saved.

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa_auth#16]
While trying to add on a new line:

`administrator|CN=ITS-Students-WebServices,OU=Groups,OU=ITS,DC=iowa,DC=uiowa,DC=edu`

to cover the student workers, the form submit seems to strip the existing line and only save the latest addition.

**Comment by richardbporter** [comment]
It does, just not mappings using the same RID: https://github.com/uiowa/uiowa_auth/blob/master/src/Form/HawkIDSettingsForm.php#L102 (which is a problem).

This is going to require an update hook to update the authmap table to reflect the data structure change.
